name: Trigger Webhook on Commit

on:
  push:
    branches:
      - "*"

jobs:
  trigger_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)"
      - name: echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - name: Trigger Webhook
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"file_name": "'"${{ steps.commit_info.outputs.file_name }}"'"}' "https://df8c-2405-201-3025-5b5d-d58c-35a-929e-49de.in.ngrok.io/update"
