name: Trigger Webhook on Commit

on:
  push:
    branches:
      - "*"

jobs:
  trigger_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: get changed files
        id: get_file
        run: |
           echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)"
      - name: echo output
        run: |
          if ${{ steps.get_file.output.files != '' }}
      - name: Trigger Webhook
        run: |
          curl -X POST -H "Content-Type: application/json"  -d '{"file_name": "'"${{ steps.get_files.output.file_name }}"'"}' "https://262b-2405-201-3025-5b5d-7d21-47f1-4089-cf6a.in.ngrok.io/update"
