name: first testing

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: install
        run: npm install
      
         
         
