name: Trigger Webhook on Commit

on:
  push:
    branches:
      - "master"

jobs:
  trigger_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)"
      - name: echo output
        run: |
          echo ${{ steps.getfile.outputs.f
